filetype off

" vim-plug
call plug#begin()
" comment a plugin to disable it on startup
Plug 'itchyny/lightline.vim'
Plug 'mengelbrecht/lightline-bufferline'
Plug 'tell-k/vim-autopep8'
Plug 'dense-analysis/ale'
Plug 'morhetz/gruvbox'
Plug 'kien/ctrlp.vim'
Plug 'xolox/vim-easytags'
Plug 'xolox/vim-misc'
Plug 'rhysd/vim-clang-format'
Plug 'easymotion/vim-easymotion'
Plug 'christoomey/vim-tmux-navigator'
Plug 'tpope/vim-fugitive'
Plug 'tpope/vim-commentary'
Plug 'tpope/vim-surround'
Plug 'tpope/vim-vinegar'
Plug 'vim-scripts/ReplaceWithRegister'
Plug 'leafoftree/vim-vue-plugin'
Plug 'joe-skb7/cscope-maps'
Plug 'NLKNguyen/c-syntax.vim' " extra C syntax highlighting
Plug 'rust-lang/rust.vim'
Plug 'majutsushi/tagbar'
Plug 'junegunn/fzf', { 'dir': '~/.fzf', 'do': './install --all' }
Plug 'junegunn/fzf.vim'
Plug 'liuchengxu/vim-clap'
call plug#end()

filetype indent on " load filetype specific indent tiles
syntax enable
colorscheme gruvbox
set background=dark

" settings
set relativenumber " relno
set clipboard=unnamedplus " use system clipboard
set completeopt+=menuone " add mucomplete to autocompleters
set tabstop=4 " number of visual spaces per tab
set ignorecase " ignore case by default while searching
set noswapfile " no swap file
set smartcase " case sensitive only when capital letters used
setl rnu " relative line number
set softtabstop=4 " number of space in tab when editing
set expandtab " tabs are spaces
set number " show line number
set showcmd " show command in bottom bar
set cursorline " highlight current line
set wildmenu " visual autocomplete for command menu
set lazyredraw " redraw only as necessary
set showmatch " hilight matching [{()}]
set incsearch " match as chars entere
set encoding=utf-8 " default encoding for new files
set hlsearch " hilight search as matches are found while typing
set laststatus=2 " start in display-status mode
set showtabline=2 " status line at top
set autoread " auto reload files from disk
set colorcolumn=80

" lightline customization
let g:lightline = {
       \ 'active': {
       \   'left': [ [ 'mode', 'paste' ],
       \             [ 'gitbranch', 'readonly', 'filename', 'modified' ] ]
       \ },
       \ 'colorscheme': 'gruvbox',
       \ 'component_function': {
       \   'gitbranch': 'fugitive#head'
       \ },
       \ }
let g:lightline.tabline = {'left': [['buffers']], 'right': [['close']]}
let g:lightline.component_expand = {'buffers': 'lightline#bufferline#buffers'}
let g:lightline.component_type   = {'buffers': 'tabsel'}

" leader mapping
let mapleader = ','

" don't close split on bd
nmap <leader>d :bprevious<CR>:bdelete #<CR>

" manage vimrc
nmap <leader>s :source ~/.vimrc<CR>
nmap <leader>e :e ~/.vimrc<CR>

" rebind save
nn <silent> <leader>w :w<CR>

" rebind escape
" imap jk <Esc>
imap kj <Esc>
imap jj <Esc>

" split navigations
nnoremap <C-J> <C-W><C-J>
nnoremap <C-K> <C-W><C-K>
nnoremap <C-L> <C-W><C-L>
nnoremap <C-H> <C-W><C-H>

" buffer navigations
nnoremap <C-n> :bnext<cr>
nnoremap <C-b> :bprev<cr>

" last focused buffer
" nnoremap <c-^> <c-Tab> 

" tpope/vim-vinegar - hide dotfiles 'gh' to goggle . hiding
let g:netrw_list_hide = '\(^\|\s\s\)\zs\.\S\+'

" joe-skb7/cscope-maps - cscope stuff
source ~/.vim/plugged/cscope-maps/plugin/cscope_maps.vim
" use cscope first, then ctags
set cscopetag

" rhysd/vim-clang-format - clang format stuff
map <C-F> :ClangFormat<cr>
imap <C-F> <c-o>:ClangFormat<cr>

"toggle relative line numbers
nn <silent> <leader>l :call ToggleNumber()<CR>

" toggle colorcolumn
nn <silent> <leader>c :call ToggleColorColumn()<CR>

" dense-analysis/ale - ale linting 
let g:ale_linters = {'python': ['pylint']}
let g:ale_python_pylint_options = '--load-plugins pylint_flask,pylint_flask_sqlalchemy'

" tpope/vim-commentary - comment strings
autocmd FileType vue setlocal commentstring=<!--\ %s\ -->
autocmd FileType c setlocal commentstring=//\ %s
" autocmd FileType c setlocal commentstring=/*\ %s\ */

" put plugins and dictionaries in this dir (also on Windows)
let vimDir = '$HOME/.vim'
let &runtimepath.=','.vimDir

" xolox/vim-easytags - easytags 
let g:easytags_async = 1

" keep undo history across sessions by storing it in a file
if has('persistent_undo')
    let myUndoDir = expand(vimDir . '/undodir')
    " Create dirs
    call system('mkdir ' . vimDir)
    call system('mkdir ' . myUndoDir)
    let &undodir = myUndoDir
    set undofile
endif

" toggle ling number style
fun! ToggleNumber() "{{{
    if exists('+relativenumber')
        :exec &nu==&rnu? "setl nu!" : "setl rnu!"
    else
        setl nu! 
    endif
endf "}}}

" toggle color column
fun! ToggleColorColumn() "{{{
    if &cc == 80
        :echo "unsetting colorcolumn"
        :exec "set colorcolumn="
    else
        :echo "setting colorcolumn"
        set colorcolumn=80
    endif
endf "}}}

" file type formats
augroup formatting
  autocmd!
  autocmd FileType c ClangFormatAutoEnable
  autocmd BufRead,BufNewFile *.json set filetype=json
  autocmd BufRead,BufNewFile *.htm,*.html setlocal tabstop=8 shiftwidth=2 softtabstop=2
  autocmd FileType python set expandtab shiftwidth=4 softtabstop=0
  autocmd FileType asm set expandtab shiftwidth=8 softtabstop=0 syntax=nasm
  autocmd FileType make set noexpandtab shiftwidth=4 softtabstop=0
  autocmd FileType vue,html,xhtml,css,xml,xslt set shiftwidth=2 softtabstop=2
  autocmd FileType json set autoindent
  autocmd FileType json set formatoptions=tcq2l
  autocmd FileType json set textwidth=78 shiftwidth=2
  autocmd FileType json set softtabstop=2 tabstop=8
  autocmd FileType json set expandtab
  autocmd FileType json set conceallevel=0
augroup END

